name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - name: Setting up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm --config.minimumReleaseAge=0 install
      - run: pnpm --config.minimumReleaseAge=0 lint
      - name: Cache pnpm modules
        uses: actions/cache@v5
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - run: pnpm --config.minimumReleaseAge=0 build
      - run: pnpm --config.minimumReleaseAge=0 test:coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
